language: r
cache: packages
sudo: false
r:
  #- oldrel
  - release
  - devel
addons:
   apt: 
      packages: libmpfr-dev 
warnings_are_errors: true
before_install:
  - tlmgr install index # for texlive and vignette?
  - R -e 'install.packages(c("Rcpp", "intervals", "adaptMCMC", "glmnet"), repos="http://cloud.r-project.org")'
  - cd C-software
  - git submodule init
  - git submodule update
  - cd ..
  - make src
  - make Rcpp
  - cd selectiveInference
